
GET http://localhost:3000/players/
###

GET http://localhost:3000/players/player_id/
###

PUT http://localhost:3000/players/player_id/
Content-Type:application/json

{
  "playerName": "Raju"
}
###

GET http://localhost:3000/matches/match_id/
###


GET http://localhost:3000/players/player_id/matches
###

GET http://localhost:3000/matches/match_id/players
###

GET http://localhost:3000/players/player_id/playerScores
###